- name: '[UTILS] Converting Server to Desktop'
  hosts: "{{ _hosts }}"
  tasks:

    - name: '[UTILS] upgrade server to desktop'
      become: true
      apt:
        name: ['ubuntu-desktop']
        state: present
        update_cache: yes