## delete the storage class

- name: '[PROVISIONER] UnDeploy ibmc-s3fs-standard Storage Class'
  hosts: localhost
  tasks:

    - include_tasks: ./config-vars.yml

    - name: '[IBM-S3] uninstall ibmc-s3fs-standard StorageClass'
      ignore_errors: yes
      command: kubectl delete -f deploy/ibmc-s3fs-standard-sc.yaml






