- name: '[k8s] Install kubectl'
  hosts: "{{ _hosts }}"
  tasks:

    - name: "[k8s] set kubectl client env on devbox"
      ignore_errors: yes
      shell: "{{ item }}"
      args:
        warn: false
      with_items:
        - mkdir -p $HOME/.kube
        - rsync -av -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --rsync-path="sudo rsync" "{{ _sudo_user }}"@"{{ groups['masters'][0] }}":/etc/kubernetes/admin.conf admin.conf
        - mv -f admin.conf ~/.kube/config

    - name: '[k8s] add environment vars to bashrc ...'
      lineinfile: dest=~/.bashrc line="export KUBECONFIG=$HOME/.kube/config" state=present
